[package]
name = "aban_rust"
version = "0.1.0"
authors = ["Sarvarian <Sarvarian@Hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.22", features = ["derive"] }
